# Build up a Pi with WireShark and VPN and as an Access Point.

# We are assuming that a desktop env is already installed.
# ??? add debian-desktop role?
---
- hosts: sharkpies
  remote_user: pi
  become: yes
  roles:
    - debian
    - AccessPoint
    - VNC
    - WireShark

...

