---
- name: Install packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - tightvncserver
      - netatalk
      - avahi-daemon

- name: VNC user directory exists
  file:
      path: /home/pi/.vnc
      state: directory
      owner: pi
      group: pi
      mode: 0700

- name: Set VNC password
  become: true
  become_user: pi
  shell: 'echo {{ vnc_password }} | vncpasswd -f > /home/pi/.vnc/passwd'
  args:
      creates: /home/pi/.vnc/passwd

- name: VNC on boot
  systemd: name=tightvncserver.service state=started enabled=yes

# Adding stuff to make it seemless with Macos Screen Sharing.
- name: Bonjour afp
  copy:
    src: afpd.service
    dest: /etc/avahi/services/afpd.service
    owner: root
    group: root
    mode: 0644
  notify:
      - restart avahi

- name: Bonjour VNC
  copy:
    src: rfb.service
    dest: /etc/avahi/services/rfb.service
    owner: root
    group: root
    mode: 0644
  notify:
      - restart avahi

...


