---
- name: Install NodeRED
  npm:
    name: node-red
    state: latest
    global: yes

# Setup user for NodeRed to run as.
- name: Add NodeRED group
  group:
      name: nodered
- name: Add NodeRED user
  user:
      name: nodered
      append: yes
      group: nodered
      groups: dialout,i2c,spi

- name: NodeRed Working dir exists
  file:
      path: /home/nodered/.node-red
      state: directory
      owner: nodered
      group: nodered
      mode: 0750

- name: Copy systemd config for NodeRED
  copy: src=nodered.service dest=/lib/systemd/system/nodered.service
  # FIXME: Is that the correct destination?

# TODO: Add to systemd so node-red starts on boot.
- name: Run NodeRED on boot
  systemd:
      name: nodered.service
      daemon_reload: yes
      enabled: yes
      state: started

# TODO: Set admin interface password.
#   ?? How best to set passwords with ansible?


# TODO: Install some node-red modules into where node-red can manage them.
# ?? Need to start nodered to get this directory?
#  /home/nodered/.node-red/ ?
#- name: Install NodeRED modules
#  npm:
#      path: /home/nodered/.node-red
#      state: latest
#      name: {{item}}
#      production: yes
#  with_items:
#    - node-red-node-serialport
#    - node-red-contrib-exosite
#    - node-red-dashboard
#    - node-red-contrib-sensortag
#    - node-red-contrib-bean
#    - node-red-smooth
#    - node-red-random
#    - node-red-pidcontrol


